[local]
command = [["func", "start"]]
background_tasks = [
    [
        "azurite",
        "--silent",
        "--location",
        ".azurite",
        "--debug",
        "$AZURITE_DEBUG_PATH",
    ],
]

[test]
command = [["ping", "localhost"]]
background_tasks = [["ping", "localhost"], ["ping", "localhost"]]

[multi]
command = [
    ["ls", "."],
    ["touch", "mk-testing-file"], 
    ["ls", "."],
    ["rm", "mk-testing-file"],
    ["ls", "."],
    ["ping", "localhost"]
]
background_tasks = [["ping", "localhost"]]

[fail]
command = [["ech", "hello"]]
