[local]
commands = [["func", "start"]]
background_tasks = [
    [
        "azurite",
        "--silent",
        "--location",
        ".azurite",
        "--debug",
        "$AZURITE_DEBUG_PATH",
    ],
]

[test]
commands = [["ping", "localhost"]]
background_tasks = [["ping", "localhost"], ["ping", "localhost"]]

[multi]
commands = [
    ["ls", "."],
    ["touch", "mk-testing-file"], 
    ["ls", "."],
    ["rm", "mk-testing-file"],
    ["ls", "."],
    ["ping", "localhost"]
]
background_tasks = [["ping", "localhost"]]

[non-env]
commands = [["echo", "$(pwd)"]]

[fail]
commands = [["ech", "hello"]]
